<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>PulseMute.ico</ApplicationIcon>
    <AssemblyName>PulseMute</AssemblyName>
    <Product>PulseMute</Product>
    <Version>1.5.3</Version>
  </PropertyGroup>
</Project>
